### ISSUE TITLE
Non Struct Response caused Panic

### ISSUE THREAD

**Issue by dstufft** [alexejk/go-xmlrpc#83]
I'm working with an XMLRPC API that has some quirks, it has two APIs one which returns a top level struct with an unknown set of members (because it's implementing a map type as a struct with variable members) and another which returns an array of structs.

In both cases, attempting to use this library causes a panic:

```go
package main

import (
	"fmt"

	"alexejk.io/go-xmlrpc"
)

func main() {
	client, _ := xmlrpc.NewClient("https://pypi.org/pypi")

	result := &[]struct {
		Name      string
		Version   string
		Timestamp string
		Action    string
		Serial    uint64
	}{}

	_ = client.Call("changelog_since_serial", &struct{ SinceSerial int }{SinceSerial: 22292800}, result)
	fmt.Printf("Items: %d\n", len(*result))
}
```

```
panic: reflect: call of reflect.Value.NumField on slice Value

goroutine 19 [running]:
reflect.flag.mustBe(...)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.21.6/libexec/src/reflect/value.go:233
reflect.Value.NumField({0x68e2a0?, 0xc00011c498?, 0x20000?})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.21.6/libexec/src/reflect/value.go:2062 +0x85
alexejk.io/go-xmlrpc.fieldsMustEqual({0x68e2a0?, 0xc00011c498?}, 0x1)
        /home/dstufft/go/pkg/mod/alexejk.io/go-xmlrpc@v0.5.1/decode.go:305 +0xf6
alexejk.io/go-xmlrpc.(*StdDecoder).Decode(0x0?, 0xc00051d460, {0x68e2a0, 0xc00011c498})
        /home/dstufft/go/pkg/mod/alexejk.io/go-xmlrpc@v0.5.1/decode.go:46 +0x45
alexejk.io/go-xmlrpc.(*Codec).ReadResponseBody(0x6a3380?, {0x68e2a0?, 0xc00011c498?})
        /home/dstufft/go/pkg/mod/alexejk.io/go-xmlrpc@v0.5.1/codec.go:171 +0x3d
net/rpc.(*Client).input(0xc0001225a0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.21.6/libexec/src/net/rpc/client.go:141 +0x291
created by net/rpc.NewClientWithCodec in goroutine 1
        /home/linuxbrew/.linuxbrew/Cellar/go/1.21.6/libexec/src/net/rpc/client.go:206 +0xb6
exit status 2
```

or

```go

package main

import (
	"fmt"

	"alexejk.io/go-xmlrpc"
)

func main() {
	client, _ := xmlrpc.NewClient("https://pypi.org/pypi")

	result := &map[string]int{}

	_ = client.Call("list_packages_with_serial", nil, result)
	fmt.Printf("Items: %d\n", len(*result))
}
```

```
panic: reflect: call of reflect.Value.NumField on map Value

goroutine 6 [running]:
reflect.flag.mustBe(...)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.21.6/libexec/src/reflect/value.go:233
reflect.Value.NumField({0x6a2380?, 0xc000088528?, 0x301e000?})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.21.6/libexec/src/reflect/value.go:2062 +0x85
alexejk.io/go-xmlrpc.fieldsMustEqual({0x68e240?, 0xc000088528?}, 0x1)
        /home/dstufft/go/pkg/mod/alexejk.io/go-xmlrpc@v0.5.1/decode.go:305 +0xf6
alexejk.io/go-xmlrpc.(*StdDecoder).Decode(0x0?, 0xc0004ac000, {0x68e240, 0xc000088528})
        /home/dstufft/go/pkg/mod/alexejk.io/go-xmlrpc@v0.5.1/decode.go:46 +0x45
alexejk.io/go-xmlrpc.(*Codec).ReadResponseBody(0x6a32e0?, {0x68e240?, 0xc000088528?})
        /home/dstufft/go/pkg/mod/alexejk.io/go-xmlrpc@v0.5.1/codec.go:171 +0x3d
net/rpc.(*Client).input(0xc0000b2600)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.21.6/libexec/src/net/rpc/client.go:141 +0x291
created by net/rpc.NewClientWithCodec in goroutine 1
        /home/linuxbrew/.linuxbrew/Cellar/go/1.21.6/libexec/src/net/rpc/client.go:206 +0xb6
exit status 2
```

**Comment by dstufft** [comment]
Ah okay, sorry about that. Thanks a lot!
